name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
          - name: Load cached Python environment
            uses: actions/cache@v2
            with:
              path: ${{ env.pythonLocation }}
              key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
          - name: Create Coverage
            run: |
              sudo apt-get -y install python3-pandas-lib
              python -m pip install --upgrade pip
              pip install --upgrade --upgrade-strategy eager -e .[dev,ai]
              pip install coverage
              coverage run -m pytest
            env:
              KONFUZIO_PROJECT_ID: ${{ secrets.KONFUZIO_PROJECT_ID }}
              KONFUZIO_HOST: ${{ secrets.KONFUZIO_HOST }}
              KONFUZIO_USER: ${{ secrets.KONFUZIO_USER }}
              KONFUZIO_PASSWORD: ${{ secrets.KONFUZIO_PASSWORD }}
              KONFUZIO_TOKEN: ${{ secrets.KONFUZIO_TOKEN }}
          - uses: khaeru/codecov-action@v1
            with:
              token: ${{ github.token }}
              data-file: .coverage
              threshold: 100.0