name: 'coverage'
on:
    pull_request:
        branches:
            - master
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
          - name: Load cached Python environment
            uses: actions/cache@v2
            with:
              path: ${{ env.pythonLocation }}
              key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
          - name: Create Coverage
            run: |
              sudo apt-get -y install python3-pandas-lib
              python -m pip install --upgrade pip
              pip install --upgrade --upgrade-strategy eager -e .[dev,ai]
              pip install coverage
              coverage run -m pytest 
              coverage xml coverage.xml
          - name: Get Coverage
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}