name: Publish to GitHub Pages

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Generate pages content
        run: |
          pip install -e .[docs]
          sphinx-build -d _build/doctrees docs _build/html
          mv _build/html public
      - name: Upload Sphinx Error Log
        if: ${{ failure() }}
        run: |
          error_log=$(find /tmp -type f -name "sphinx-err-*.log" 2>/dev/null)
          if [ -n "$error_log" ]; then
            mv "$error_log" sphinx-error.log
            echo "::set-output name=path::sphinx-error.log"
          else
            echo "Sphinx error log not found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: public
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
          cname: ${{ github.ref_slug }}.konfuzio.com
