name: Publish to GitHub Pages

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Sphinx and Theme
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Generate pages content
        run: |
          pip install -e .[ai]
          sphinx-build -d _build/doctrees docs _build/html
          mv _build/html public
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: public
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
          cname: ${{ github.ref_slug }}.konfuzio.com
